### ISSUE TITLE
User information

### ISSUE THREAD

**Issue by Sivannamma** [aviv1620/GeekFindLove#4]
In the firebase we need to update the field where the user finished answering the information details.
we updated it in the program but we need to do "update" in the tree.
That way we know that the user finished the registeration even if he quitted in the middle.

**Comment by aviv1620** [comment]
not need finished_registration flag. we simple check if is exist in FireBase RealTime tree or not.

FirstTimeLogin.java line 80.
`user.setId(userId); // user id is the key.`
now we use user id and not make new one.
**note: i remove the old user in FireBase RealTime tree. they need first time sign in again**

in MainActivity.java line 116
` if(userInformation == null)`
if userInformation is null this meen the user not finished registration.

**Comment by aviv1620** [comment]
p.s.
now also the user not enter the email again. We simply import the email from authentication.

**Comment by aviv1620** [comment]
explain
