### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by Sivannamma** [aviv1620/GeekFindLove#5]
we succeeded making fragments, we need to create all of them , for each of them the right features.

**Comment by aviv1620** [comment]
add PickUpLineFragment by use  
right click>new>fragmen>gallery>list
90% code generate automaticly.

**Comment by aviv1620** [comment]
add fragment matching item in same way. and design fragment_matching_item.xml

**Comment by aviv1620** [comment]
i add tabbed activity.

rigiht click>new>activity>gallery>tabbed activity

com.example.geekfindlove.MainActivity#onDataChange
UserActivity.class to UserActivity1.class
com.example.geekfindlove.FirstTimeLogin#completionListener
UserActivity.class to UserActivity1.class


com.example.geekfindlove.ui.main.SectionsPagerAdapter#TAB_TITLES
com.example.geekfindlove.ui.main.SectionsPagerAdapter#getItem


values/strings.xml:7
values/strings.xml:8
values/strings.xml:9
values/strings.xml:20

com.example.geekfindlove.profile_fragment#newInstance
com.example.geekfindlove.questions_fragment#newInstance

**Comment by aviv1620** [comment]
done
